/**
 * Human-readable companion for the generated config. Keep sections in the same order as the
 * public schema so users can map each explanation directly to `.ccr/config.json`.
 */

export const CONFIG_MANUAL = `# CCR configuration manual

This file explains every setting in \`.ccr/config.json\`. It is generated by \`ccr config init --apply\`
and is a reference for humans. Re-running that command may refresh this manual. The JSON file itself
is human-owned: CCR, Claude, and other AI
coding agents must not change it without your explicit approval of the exact setting and value.

Keep the keys in this order. Run \`ccr config validate\` after editing, then run \`ccr setup --apply\`
to refresh skills and instruction files. Run \`/ccr-hooks sync\` in Claude Code after changing an
enabled hook policy.

## \`domain\`

- Default: \`"unspecified"\`
- Values: a short name from 1 to 80 characters, such as \`civic-tech\` or \`education\`.
- Effect: tells the context skill the repository domain when it interprets the project. CCR never
  changes this value automatically.

Example: \`ccr config set domain civic-tech --apply\`

## \`hooks\`

### \`hooks.enabled\`

- Default: \`true\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: \`/ccr-context initialize\` invokes \`/ccr-hooks sync\`. The skill inspects
  repository hook conventions before choosing how to install advisory \`pre-commit\` and
  \`post-commit\` checks. Effect when \`false\`: initialization skips hook sync and setup removes
  legacy CCR-managed hook blocks. Package installation never installs hooks by itself.

Example: \`ccr config set hooks.enabled false --apply\`

### \`hooks.checkBeforeCommit\`

- Default: \`true\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: the advisory pre-commit hook warns when repository files are staged
  without staged shared context. Effect when \`false\`: that warning is skipped. This setting
  has no effect while \`hooks.enabled\` is \`false\`.

Example: \`ccr config set hooks.checkBeforeCommit false --apply\`

### \`hooks.autoUpdateContext\`

- Default: \`false\`.
- Values: \`true\` or \`false\`.
- Effect when \`true\`: an enabled post-commit hook runs Claude Code headlessly when repository
  changes need continuity work. It completes the existing commit journal and updates only justified
  shared context. Successful commits are recorded locally so one commit is not processed twice.
  Automation never stages, commits, amends, resets, or pushes; context edits remain visible for
  human review and a later commit. Effect when \`false\`: hooks remain advisory.
- Requirements: Claude Code must be installed and authenticated. Failure is non-blocking and prints
  the manual \`/ccr-context update\` fallback.

Example: \`ccr config set hooks.autoUpdateContext true --apply\`

## \`context\`

### \`context.recentJournalEntries\`

- Default: \`3\`
- Values: an integer from 1 to 10.
- Effect: controls how many recent local continuity journal entries every context operation and
  review must read before planning. Branch reviews read that branch's entries; PR reviews read the
  selected PR's isolated entries. A higher value gives more continuity; a lower value keeps the
  prompt smaller.

Example: \`ccr config set context.recentJournalEntries 5 --apply\`

### \`context.maxCompactionPercent\`

- Default: \`25\`
- Values: an integer from 20 to 30.
- Effect: limits how much \`/ccr-context compact\` may remove in one run. CCR keeps the
  reduction bounded so compaction does not erase too much project knowledge at once.

Example: \`ccr config set context.maxCompactionPercent 20 --apply\`

## \`instructions\`

### \`instructions.updateClaudeMd\`

- Default: \`false\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: setup may add or maintain CCR's small managed block in the repository
  root \`CLAUDE.md\`. Effect when \`false\`: setup leaves \`CLAUDE.md\` alone.

Example: \`ccr config set instructions.updateClaudeMd true --apply\`

### \`instructions.updateAgentsMd\`

- Default: \`false\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: setup may add or maintain the same small managed block in the repository
  root \`AGENTS.md\`. Effect when \`false\`: setup leaves \`AGENTS.md\` alone.

Example: \`ccr config set instructions.updateAgentsMd true --apply\`

### \`instructions.updateDecisionsMd\`

- Default: \`false\`.
- Values: \`true\` or \`false\`.
- Effect when \`true\`: CCR review or context update may record at most one human-confirmed, durable
  decision through \`ccr context append-decision\`. A finding alone is not a decision. Effect when
  \`false\`: that command rejects every write and CCR leaves \`.ccr/decisions.md\` untouched. CCR
  never replaces or removes human entries.

Example: \`ccr config set instructions.updateDecisionsMd true --apply\`

## Applying changes

1. Edit \`.ccr/config.json\` or use \`ccr config set <key> <value> --apply\`.
2. Run \`ccr config validate\`.
3. Run \`ccr setup --apply\` so setup refreshes skills and instruction files.
4. If an enabled hook setting changed, run \`/ccr-hooks sync\` in Claude Code.

Runtime privacy exclusions are fixed safety defaults, not editable keys in this file.
`;
