/**
 * Human-readable companion for the generated config. Keep sections in the same order as the
 * public schema so users can map each explanation directly to `.ccr/config.json`.
 */

export const CONFIG_MANUAL = `# CCR configuration manual

This file explains every setting in \`.ccr/config.json\`. It is generated by \`ccr config init\`
and is a reference for humans. Re-running that command may refresh this manual. The JSON file itself
is human-owned: CCR, Claude, and other AI coding agents must not change it without your explicit
approval of the exact setting and value, except for the one-time initial-domain classification below.

Keep the keys in this order and run \`ccr config validate\` after editing. Most settings take effect
immediately. Run \`ccr setup\` only for an \`instructions.updateClaudeMd\` or
\`instructions.updateAgentsMd\` change. Hook installation is managed separately as described below.

## \`domain\`

- Default: \`"unspecified"\`
- Values: a short name from 1 to 80 characters, such as \`civic-tech\` or \`education\`.
- Effect: tells the context skill the repository domain when it interprets the project. During the
  first \`/ccr-context initialize\` only, CCR replaces the untouched \`"unspecified"\` default with a
  concise, evidence-backed product-domain label (or \`general-software\` if no specific domain is
  established). It uses a conditional updater that preserves any human-set value. Later operations
  never change the domain automatically.

Example: \`ccr config set domain civic-tech\`

## \`hooks\`

### \`hooks.enabled\`

- Default: \`true\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: run \`/ccr-hooks sync\` to install or refresh repository-native advisory
  \`pre-commit\` and \`post-commit\` integration; initialization does this once automatically.
- Effect when \`false\`: run \`/ccr-hooks remove\` to remove repository-native integration. Setup
  removes only legacy direct CCR hook blocks. Package installation never installs hooks by itself.

Example: \`ccr config set hooks.enabled false\`

### \`hooks.checkBeforeCommit\`

- Default: \`true\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: the advisory pre-commit hook warns when repository files are staged
  without staged shared context. Effect when \`false\`: that warning is skipped. This setting
  has no effect while \`hooks.enabled\` is \`false\`.

Example: \`ccr config set hooks.checkBeforeCommit false\`

### \`hooks.autoUpdateContext\`

- Default: \`false\`.
- Values: \`true\` or \`false\`.
- Effect when \`true\`: an enabled post-commit hook runs Claude Code headlessly when repository
  changes need continuity work. CCR places bounded, privacy-approved exact-commit evidence in a
  temporary ignored \`.ccr/private/\` packet. Headless Claude can read only approved \`.ccr\` inputs
  and edit only the exact commit journal and \`.ccr/project.md\`, plus \`.ccr/decisions.md\` when its
  separate opt-in is true. Any \`project.md\` edit is limited to durable, evidence-backed
  product-to-people behavior or constraints, not a technical summary. It receives no shell or raw
  repository access. Successful commits are
  recorded locally so one commit is not processed twice. Automation never stages, commits, amends,
  resets, or pushes; failures clean the packet, remain non-blocking, and leave the manual fallback.
  Effect when \`false\`: hooks remain advisory.
- Requirements: Claude Code must be installed and authenticated. Failure is non-blocking and prints
  the manual \`/ccr-context update\` fallback.

Example: \`ccr config set hooks.autoUpdateContext true\`

## \`context\`

### \`context.recentJournalEntries\`

- Default: \`3\`
- Values: an integer from 1 to 10.
- Effect: controls how many recent local continuity journal entries every context operation and
  review must read before planning. CCR selects the repository-wide latest entries by validated
  \`Updated\` metadata, regardless of their branch or pull-request directory. A higher value gives
  more continuity; a lower value keeps the prompt smaller. Equal \`Updated\` values sort by
  \`Started\` newest-first, then repository path for a deterministic tie. Until a legacy journal is
  reused and migrated, its single valid \`Timestamp\` is treated as both \`Started\` and \`Updated\`.

Example: \`ccr config set context.recentJournalEntries 5\`

### \`context.maxCompactionPercent\`

- Default: \`25\`
- Values: an integer from 20 to 30.
- Effect: limits how much \`/ccr-context compact\` may remove in one run. CCR keeps the
  reduction bounded so compaction does not erase too much project knowledge at once.

Example: \`ccr config set context.maxCompactionPercent 20\`

## \`instructions\`

### \`instructions.updateClaudeMd\`

- Default: \`false\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: setup may add or maintain CCR's small managed block in the repository
  root \`CLAUDE.md\`. Effect when \`false\`: setup leaves \`CLAUDE.md\` alone.

Example: \`ccr config set instructions.updateClaudeMd true\`

### \`instructions.updateAgentsMd\`

- Default: \`false\`
- Values: \`true\` or \`false\`.
- Effect when \`true\`: setup may add or maintain the same small managed block in the repository
  root \`AGENTS.md\`. Effect when \`false\`: setup leaves \`AGENTS.md\` alone.

Example: \`ccr config set instructions.updateAgentsMd true\`

### \`instructions.updateDecisionsMd\`

- Default: \`false\`.
- Values: \`true\` or \`false\`.
- Effect when \`true\`: an interactive review or context operation may append at most one bounded,
  non-duplicate durable decision through \`ccr context append-decision\`. A headless post-commit
  update has no shell, so it may make the same single append directly; CCR validates that edit as
  append-only. A finding alone is not a decision.
- Effect when \`false\`: interactive and headless decision writes are rejected. CCR never replaces
  or removes existing entries.

Example: \`ccr config set instructions.updateDecisionsMd true\`

## Applying changes

1. Edit \`.ccr/config.json\` or use \`ccr config set <key> <value>\`.
2. Run \`ccr config validate\`.
3. For \`instructions.updateClaudeMd\` or \`instructions.updateAgentsMd\`, run \`ccr setup\`.
4. After enabling hooks, run \`/ccr-hooks sync\`; after disabling them, run \`/ccr-hooks remove\`.

All other settings apply immediately. Existing hook integration reads
\`hooks.checkBeforeCommit\` and \`hooks.autoUpdateContext\` at runtime.

Runtime privacy exclusions are fixed safety defaults, not editable keys in this file.
`;
